[package]
name = "rtools-wasm"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
description = "WASM bindings for rtools"
readme = "../../README.md"
keywords = ["rtools", "wasm", "webassembly", "image"]
categories = ["wasm"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
image = { workspace = true }
wasm-bindgen = { workspace = true }
serde_json = { workspace = true }
serde-wasm-bindgen = { workspace = true }

[dev-dependencies]
wasm-bindgen-test = "0.3"

[lints]
workspace = true
